// ============================================================
//  EMRS SCHOOL CREDENTIALS
//  17 EMRS Schools – Assam
//  Each school gets a unique username + password
//  Role: "school" → sees EMRSForm pre-filled with school info
//  Role: "admin"  → sees EMRSAdminDashboard (all 17 schools)
//
//  ⚠️  IMPORTANT: schoolName must EXACTLY match the `value`
//      field in EMRS_SCHOOLS (SchoolDetails.jsx) so auto-fill
//      works correctly on login.
// ============================================================

export const ADMIN_CREDENTIALS = {
  username: "emrs_admin_assam",
  password: "Admin@EMRS2024",
  role: "admin",
  name: "EMRS Admin – Assam",
};

export const SCHOOL_CREDENTIALS = [
  {
    id: 1,
    username: "emrs_jalah",
    password: "Jalah@2024",
    role: "school",
    schoolCode: "EMRS-AS-01",
    schoolName: "EMRS, Jalah, Vill. Daodhara",   // ← matches EMRS_SCHOOLS value
    district: "Baksa",
    block: "Jalah",
    gramPanchayat: "Daodhara",
    village: "Daodhara",
    pincode: "781372",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 2,
    username: "emrs_bajali",
    password: "Bajali@2024",
    role: "school",
    schoolCode: "EMRS-AS-02",
    schoolName: "EMRS,Kharadhara",               // ← matches EMRS_SCHOOLS value
    district: "Bajali",
    block: "Pathsala",
    gramPanchayat: "Kharadhara",
    village: "Kharadhara",
    pincode: "781325",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 3,
    username: "emrs_howraghat",
    password: "Howraghat@2024",
    role: "school",
    schoolCode: "EMRS-AS-03",
    schoolName: "EMRS, Howraghat",               // ← matches EMRS_SCHOOLS value
    district: "Karbi Anglong",
    block: "Howraghat",
    gramPanchayat: "Howraghat",
    village: "Howraghat",
    pincode: "782480",
    yearOfSanction: "2021-22",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 4,
    username: "emrs_jonai",
    password: "Jonai@2024",
    role: "school",
    schoolCode: "EMRS-AS-04",
    schoolName: "EMRS, Jonai, Vill. Purana Jhelom", // ← matches EMRS_SCHOOLS value
    district: "Dhemaji",
    block: "Jonai",
    gramPanchayat: "Purana Jhelom",
    village: "Purana Jhelom",
    pincode: "787060",
    yearOfSanction: "2021-22",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 5,
    username: "emrs_ardaopur",
    password: "Ardaopur@2024",
    role: "school",
    schoolCode: "EMRS-AS-05",
    schoolName: "EMRS,Haflong, Vill. Ardaopur",  // ← matches EMRS_SCHOOLS value
    district: "Dima Hasao",
    block: "Haflong",
    gramPanchayat: "Ardaopur",
    village: "Ardaopur",
    pincode: "788819",
    yearOfSanction: "2018-19",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 6,
    username: "emrs_Dalbari",
    password: "Dalbari@2024",
    role: "school",
    schoolCode: "EMRS-AS-06",
    schoolName: "EMRS, Dalbari, Barama",         // ← matches EMRS_SCHOOLS value
    district: "Baksa",
    block: "Barama",
    gramPanchayat: "Dalbari",
    village: "Dalbari",
    pincode: "781346",
    yearOfSanction: "2010-11",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 7,
    username: "emrs_sarupeta",
    password: "Sarupeta@2024",
    role: "school",
    schoolCode: "EMRS-AS-07",
    schoolName: "EMRS, Sarupeta, Vill. Tatikuchi", // ← matches EMRS_SCHOOLS value
    district: "Baksa",
    block: "Sarupeta",
    gramPanchayat: "Tatikuchi",
    village: "Tatikuchi",
    pincode: "781317",
    yearOfSanction: "2023-24",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 8,
    username: "emrs_bedlangmari",
    password: "Bedlangmari@2024",
    role: "school",
    schoolCode: "EMRS-AS-08",
    schoolName: "EMRS, Bedlangmari",             // ← matches EMRS_SCHOOLS value
    district: "Kokrajhar",
    block: "Kokrajhar",
    gramPanchayat: "Bedlangmari",
    village: "Bedlangmari",
    pincode: "783370",
    yearOfSanction: "2016-17",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 9,
    username: "emrs_phuloni",
    password: "Phuloni@2024",
    role: "school",
    schoolCode: "EMRS-AS-09",
    schoolName: "EMRS, Phuloni, Vill. Donghap",  // ← matches EMRS_SCHOOLS value
    district: "Karbi Anglong",
    block: "Diphu",
    gramPanchayat: "Donghap",
    village: "Donghap",
    pincode: "782460",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 10,
    username: "emrs_silonijan",
    password: "Silonijan@2024",
    role: "school",
    schoolCode: "EMRS-AS-10",
    schoolName: "EMRS, Silonijan, Vill. Thengkur Terang", // ← matches EMRS_SCHOOLS value
    district: "Karbi Anglong",
    block: "Silonijan",
    gramPanchayat: "Thengkur Terang",
    village: "Thengkur Terang",
    pincode: "782470",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 11,
    username: "emrs_donka",
    password: "Donka@2024",
    role: "school",
    schoolCode: "EMRS-AS-11",
    schoolName: "EMRS, Donka, Vill. Taralangso NC", 
    district: "West Karbi Anglong",
    block: "Donka",
    gramPanchayat: "Taralangso NC",
    village: "Taralangso NC",
    pincode: "782448",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 12,
    username: "emrs_Umrangso",
    password: "Umrangso@2024",
    role: "school",
    schoolCode: "EMRS-AS-12",
    schoolName: "EMRS,Umrangso, Vill. Taisiling Hower", // ← matches EMRS_SCHOOLS value
    district: "Dima Hasao",
    block: "Umrangso",
    gramPanchayat: "Taisiling Hower",
    village: "Taisiling Hower",
    pincode: "788931",
    yearOfSanction: "2022-23",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 13,
    username: "emrs_Harangajao",
    password: "Harangajao@2024",
    role: "school",
    schoolCode: "EMRS-AS-13",
    schoolName: "EMRS, Harangajao, Vill. Dolaidisa", // ← matches EMRS_SCHOOLS value
    district: "Dima Hasao",
    block: "Harangajao",
    gramPanchayat: "Dolaidisa",
    village: "Dolaidisa",
    pincode: "788830",
    yearOfSanction: "2024-25",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 14,
    username: "emrs_diyungbra",
    password: "Diyungbra@2024",
    role: "school",
    schoolCode: "EMRS-AS-14",
    schoolName: "EMRS, Diyungbra, Vill. Larbo",  // ← matches EMRS_SCHOOLS value
    district: "Dima Hasao",
    block: "Diyungbra",
    gramPanchayat: "Larbo",
    village: "Larbo",
    pincode: "788820",
    yearOfSanction: "2024-25",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 15,
    username: "emrs_boko",
    password: "Boko@2024",
    role: "school",
    schoolCode: "EMRS-AS-15",
    schoolName: "EMRS, Boko, Vill. Nagopara",    
    district: "Kamrup",
    block: "Boko",
    gramPanchayat: "Nagopara",
    village: "Nagopara",
    pincode: "781123",
    yearOfSanction: "2022-23",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 16,
    username: "emrs_dudhnoi",
    password: "Dudhnoi@2024",
    role: "school",
    schoolCode: "EMRS-AS-16",
    schoolName: "EMRS, Dudhnoi, Vill. Jakhuwapara", // ← matches EMRS_SCHOOLS value
    district: "Goalpara",
    block: "Dudhnoi",
    gramPanchayat: "Jakhuwapara",
    village: "Jakhuwapara",
    pincode: "783124",
    yearOfSanction: "2022-23",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
  {
    id: 17,
    username: "emrs_khoirabari",
    password: "Khoirabari@2024",
    role: "school",
    schoolCode: "EMRS-AS-17",
    schoolName: "EMRS, Khoirabari, Vill. Malmura", // ← matches EMRS_SCHOOLS value
    district: "Udalguri",
    block: "Khoirabari",
    gramPanchayat: "Malmura",
    village: "Malmura",
    pincode: "784150",
    yearOfSanction: "2025-26",
    principal: "",
    contact: "",
    email: "",
    state: "Assam",
  },
];

// ── Helper: find user by username + password ──────────────────────────────────
export const authenticateUser = (username, password) => {
  if (
    username === ADMIN_CREDENTIALS.username &&
    password === ADMIN_CREDENTIALS.password
  ) {
    return { ...ADMIN_CREDENTIALS };
  }
  const school = SCHOOL_CREDENTIALS.find(
    (s) => s.username === username && s.password === password
  );
  return school || null;
};