// ============================================================
//  EMRS SCHOOL CREDENTIALS
//  17 EMRS Schools – Assam
//  Each school gets a unique username + password
//  Role: "school" → sees EMRSForm pre-filled with school info
//  Role: "admin"  → sees EMRSAdminDashboard (all 17 schools)
// ============================================================

export const ADMIN_CREDENTIALS = {
  username: "emrs_admin_assam",
  password: "Admin@EMRS2024",
  role: "admin",
  name: "EMRS Admin – Assam",
};

export const SCHOOL_CREDENTIALS = [
  {
    id: 1,
    username: "emrs_jalah",
    password: "Jalah@2024",
    role: "school",
    schoolCode: "EMRS-AS-01",
    schoolName: "EMRS, Jalah (Baksa)",
    district: "Baksa",
    block: "Jalah",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    village: "Jalah",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 2,
    username: "emrs_bajali",
    password: "Bajali@2024",
    role: "school",
    schoolCode: "EMRS-AS-02",
    schoolName: "EMRS, Kharadhara (Bajali)",
    district: "Baksa",
    block: "Bajali",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    village: "Bajali",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 3,
    username: "emrs_howraghat",
    password: "Howraghat@2024",
    role: "school",
    schoolCode: "EMRS-AS-03",
    schoolName: "EMRS, Howraghat (Karbi Anglong)",
    district: "Karbi Anglong",
    block: "",
    yearOfSanction: "2021-22",
    principal: "",
    contact: "",
    email: "",
    village: "Howraghat",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 4,
    username: "emrs_jonai",
    password: "Jonai@2024",
    role: "school",
    schoolCode: "EMRS-AS-04",
    schoolName: "EMRS, Jonai (Dhemaji)",
    district: "Dhemaji",
    block: "",
    yearOfSanction: "2021-22",
    principal: "",
    contact: "",
    email: "",
    village: "Purana Jhelom",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 5,
    username: "emrs_ardaopur",
    password: "Ardaopur@2024",
    role: "school",
    schoolCode: "EMRS-AS-05",
    schoolName: "EMRS, Ardaopur (Dima Hasao)",
    district: "Dima Hasao",
    block: "Haflong",
    yearOfSanction: "2018-19",
    principal: "",
    contact: "",
    email: "",
    village: "Ardaopur",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 6,
    username: "emrs_Dalbari",
    password: "Dalbari@2024",
    role: "school",
    schoolCode: "EMRS-AS-06",
    schoolName: "EMRS, Dalbari (Barama)",
    district: "Baksa",
    block: "Barama",
    yearOfSanction: "2010-11",
    principal: "",
    contact: "",
    email: "",
    village: "Dalbari",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 7,
    username: "emrs_sarupeta",
    password: "Sarupeta@2024",
    role: "school",
    schoolCode: "EMRS-AS-07",
    schoolName: "EMRS, Sarupeta (Baksa)",
    district: "Baksa",
    block: "",
    yearOfSanction: "2023-24",
    principal: "",
    contact: "",
    email: "",
    village: "Tatikuchi",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 8,
    username: "emrs_bedlangmari",
    password: "Bedlangmari@2024",
    role: "school",
    schoolCode: "EMRS-AS-08",
    schoolName: "EMRS, Bedlangmari (Kokrajhar)",
    district: "Kokrajhar",
    block: "",
    yearOfSanction: "2016-17",
    principal: "",
    contact: "",
    email: "",
    village: "",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 9,
    username: "emrs_phuloni",
    password: "Phuloni@2024",
    role: "school",
    schoolCode: "EMRS-AS-09",
    schoolName: "EMRS, Phuloni (Karbi Anglong)",
    district: "Karbi Anglong",
    block: "Diphu",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    village: "Donghap",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 10,
    username: "emrs_silonijan",
    password: "Silonijan@2024",
    role: "school",
    schoolCode: "EMRS-AS-10",
    schoolName: "EMRS, Silonijan (West Karbi Anglong)",
    district: "West Karbi Anglong",
    block: "",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    village: "Thengkur Terang",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 11,
    username: "emrs_donka",
    password: "Donka@2024",
    role: "school",
    schoolCode: "EMRS-AS-11",
    schoolName: "EMRS, Donka (West Karbi Anglong)",
    district: "West Karbi Anglong",
    block: "",
    yearOfSanction: "2020-21",
    principal: "",
    contact: "",
    email: "",
    village: "Taralangso",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 12,
    username: "emrs_Umrangso",
    password: "Umrangso@2024",
    role: "school",
    schoolCode: "EMRS-AS-12",
    schoolName: "EMRS, Umrangso (Dima Hasao)",
    district: "Dima Hasao",
    block: "",
    yearOfSanction: "2022-23",
    principal: "",
    contact: "",
    email: "",
    village: "Taisiling Hower",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 13,
    username: "emrs_Harangajao",
    password: "Harangajao@2024",
    role: "school",
    schoolCode: "EMRS-AS-13",
    schoolName: "EMRS, Harangajao (Dima Hasao)",
    district: "Dima Hasao",
    block: "",
    yearOfSanction: "2024-25",
    principal: "",
    contact: "",
    email: "",
    village: "Dolaidisa",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 14,
    username: "emrs_diyungbra",
    password: "Diyungbra@2024",
    role: "school",
    schoolCode: "EMRS-AS-14",
    schoolName: "EMRS, Diyungbra (Dima Hasao)",
    district: "Dima Hasao",
    block: "",
    yearOfSanction: "2024-25",
    principal: "",
    contact: "",
    email: "",
    village: "Larbo",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 15,
    username: "emrs_boko",
    password: "Boko@2024",
    role: "school",
    schoolCode: "EMRS-AS-15",
    schoolName: "EMRS, Boko (Kamrup)",
    district: "Kamrup",
    block: "",
    yearOfSanction: "2022-23",
    principal: "",
    contact: "",
    email: "",
    village: "Nagopara",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 16,
    username: "emrs_dudhnoi",
    password: "Dudhnoi@2024",
    role: "school",
    schoolCode: "EMRS-AS-16",
    schoolName: "EMRS, Dudhnoi (Goalpara)",
    district: "Goalpara",
    block: "",
    yearOfSanction: "2022-23",
    principal: "",
    contact: "",
    email: "",
    village: "Jakhuwapara",
    gramPanchayat: "",
    state: "Assam",
  },
  {
    id: 17,
    username: "emrs_khoirabari",
    password: "Khoirabari@2024",
    role: "school",
    schoolCode: "EMRS-AS-17",
    schoolName: "EMRS, Khoirabari (Udalguri)",
    district: "Udalguri",
    block: "",
    yearOfSanction: "2025-26",
    principal: "",
    contact: "",
    email: "",
    village: "Malmura",
    gramPanchayat: "",
    state: "Assam",
  },
];

// ── Helper: find user by username + password ──
export const authenticateUser = (username, password) => {
  if (
    username === ADMIN_CREDENTIALS.username &&
    password === ADMIN_CREDENTIALS.password
  ) {
    return { ...ADMIN_CREDENTIALS };
  }
  const school = SCHOOL_CREDENTIALS.find(
    (s) => s.username === username && s.password === password
  );
  return school || null;
};